{% set name = "dataretrieval" %}
{% set version = "1.0.11" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/dataretrieval-{{ version }}.tar.gz
  sha256: b6a8c0336c98572047b366f01ddb1870ed5a0ea2a41e8cb4c6e18174bacf3939

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - pip
    - setuptools
    - python >=3.6
  run:
    - pandas
    - python >=3.6
    - requests

test:
  imports:
    - dataretrieval
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://pypi.org/project/dataretrieval/
  license: CC0-1.0
  license_file: LICENSE.md
  summary: Package to obtain USGS or EPA water quality, streamflow, and metadata from web services.

extra:
  recipe-maintainers:
    - thodson-usgs
    - elbeejay
    - jsta
