{% set name = "dataretrieval" %}
{% set version = "1.0.9" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/dataretrieval-{{ version }}.tar.gz
  sha256: 5597d82f33fb2df9e43d555e6106ec8f950e1cd96cda11f2e739bfc91b7191b0

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - pip
    - python >=3.6
  run:
    - pandas
    - python >=3.6
    - requests

test:
  imports:
    - dataretrieval
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://pypi.org/project/dataretrieval/
  license: CC0-1.0
  license_file: LICENSE.md
  summary: Package to obtain USGS or EPA water quality, streamflow, and metadata from web services.

extra:
  recipe-maintainers:
    - thodson-usgs
    - elbeejay
    - jsta
